// AuraMain.swift
// `@main` entry point for the Aura iOS app target generated by xcodegen.
//
// This file is intentionally excluded from the Swift Package build (see
// `Package.swift` `exclude:`) because the SPM build ships `Aura` as a
// library — libraries cannot declare `@main`. The Xcode app target picks
// this file up to wire `AuraApp` (defined in `AuraApp.swift`) as the
// process entrypoint.
import SwiftUI

@available(iOS 17.0, *)
@main
struct AuraAppMain: App {
	@StateObject private var silenceBudget = SilenceBudget()

	var body: some Scene {
		WindowGroup {
			RootTabView()
				.environmentObject(silenceBudget)
				.tint(Color("AccentColor"))
		}
	}
}
